[package]
name = "rasmus_og_monopolet"
version = "0.1.0"
authors = ["Philip Munksgaard <philip@munksgaard.me>"]
edition = "2018"

[dependencies]
actix-web = "0.7.13"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
envy = "0.3.3"
reqwest = "0.9.4"
log = "0.4.7"
env_logger = "0.6.2"
